
package com.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.5.0
 * Thu Sep 29 10:07:53 CEST 2016
 * Generated source version: 2.5.0
 */

@XmlRootElement(name = "getUsuariosListResponse", namespace = "http://service.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getUsuariosListResponse", namespace = "http://service.com/")

public class GetUsuariosListResponse {

    @XmlElement(name = "Usuario")
    private java.util.List<com.modelo.Usuario> Usuario;

    public java.util.List<com.modelo.Usuario> getUsuario() {
        return this.Usuario;
    }

    public void setUsuario(java.util.List<com.modelo.Usuario> newUsuario)  {
        this.Usuario = newUsuario;
    }

}

