
package com.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.5.0
 * Thu Sep 29 10:07:54 CEST 2016
 * Generated source version: 2.5.0
 */

@XmlRootElement(name = "updateUsuarioResponse", namespace = "http://service.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateUsuarioResponse", namespace = "http://service.com/")

public class UpdateUsuarioResponse {

    @XmlElement(name = "Respuesta")
    private com.modelo.Respuesta Respuesta;

    public com.modelo.Respuesta getRespuesta() {
        return this.Respuesta;
    }

    public void setRespuesta(com.modelo.Respuesta newRespuesta)  {
        this.Respuesta = newRespuesta;
    }

}

