
package com.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.0
 * 2016-09-29T10:08:11.070+02:00
 * Generated source version: 2.5.0
 */

@WebFault(name = "IOException", targetNamespace = "http://service.com/")
public class IOException_Exception extends Exception {
    
    private com.service.IOException ioException;

    public IOException_Exception() {
        super();
    }
    
    public IOException_Exception(String message) {
        super(message);
    }
    
    public IOException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public IOException_Exception(String message, com.service.IOException ioException) {
        super(message);
        this.ioException = ioException;
    }

    public IOException_Exception(String message, com.service.IOException ioException, Throwable cause) {
        super(message, cause);
        this.ioException = ioException;
    }

    public com.service.IOException getFaultInfo() {
        return this.ioException;
    }
}
