package com.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2016-09-29T10:08:11.090+02:00
 * Generated source version: 2.5.0
 * 
 */
@WebService(targetNamespace = "http://service.com/", name = "UsuarioServcice")
@XmlSeeAlso({ObjectFactory.class})
public interface UsuarioServcice {

    @WebMethod(action = "urn:GetUsuariosList")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getUsuariosListResponse", targetNamespace = "http://service.com/", partName = "parameters")
    public GetUsuariosListResponse getUsuariosList(
        @WebParam(partName = "parameters", name = "getUsuariosList", targetNamespace = "http://service.com/")
        GetUsuariosList parameters
    );

    @WebMethod(action = "urn:AddUsuario")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "addUsuarioResponse", targetNamespace = "http://service.com/", partName = "parameters")
    public AddUsuarioResponse addUsuario(
        @WebParam(partName = "parameters", name = "addUsuario", targetNamespace = "http://service.com/")
        AddUsuario parameters
    );

    @WebMethod(action = "urn:UpdateUsuario")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "updateUsuarioResponse", targetNamespace = "http://service.com/", partName = "parameters")
    public UpdateUsuarioResponse updateUsuario(
        @WebParam(partName = "parameters", name = "updateUsuario", targetNamespace = "http://service.com/")
        UpdateUsuario parameters
    ) throws IOException_Exception;

    @WebMethod
    @RequestWrapper(localName = "setUsuariosList", targetNamespace = "http://service.com/", className = "com.service.SetUsuariosList")
    @ResponseWrapper(localName = "setUsuariosListResponse", targetNamespace = "http://service.com/", className = "com.service.SetUsuariosListResponse")
    public void setUsuariosList(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.service.Usuario> arg0
    );

    @WebMethod(action = "urn:GetUsuario")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getUsuarioResponse", targetNamespace = "http://service.com/", partName = "parameters")
    public GetUsuarioResponse getUsuario(
        @WebParam(partName = "parameters", name = "getUsuario", targetNamespace = "http://service.com/")
        GetUsuario parameters
    );

    @WebMethod
    @RequestWrapper(localName = "checkCallWS", targetNamespace = "http://service.com/", className = "com.service.CheckCallWS")
    @ResponseWrapper(localName = "checkCallWSResponse", targetNamespace = "http://service.com/", className = "com.service.CheckCallWSResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.service.Respuesta checkCallWS(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod(action = "urn:DeleteUsuario")
    @RequestWrapper(localName = "deleteUsuario", targetNamespace = "http://service.com/", className = "com.service.DeleteUsuario")
    @ResponseWrapper(localName = "deleteUsuarioResponse", targetNamespace = "http://service.com/", className = "com.service.DeleteUsuarioResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean deleteUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        com.service.Usuario arg0
    );
}
