
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2016-09-29T10:08:11.078+02:00
 * Generated source version: 2.5.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "UsuarioServciceService",
                      portName = "UsuarioServcicePort",
                      targetNamespace = "http://service.com/",
                      wsdlLocation = "http://localhost:8080/CRUDWSBBDD/services/UsuarioServcicePort?wsdl",
                      endpointInterface = "com.service.UsuarioServcice")
                      
public class UsuarioServciceImpl implements UsuarioServcice {

    private static final Logger LOG = Logger.getLogger(UsuarioServciceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.service.UsuarioServcice#getUsuariosList(com.service.GetUsuariosList  parameters )*
     */
    public com.service.GetUsuariosListResponse getUsuariosList(GetUsuariosList parameters) { 
        LOG.info("Executing operation getUsuariosList");
        System.out.println(parameters);
        try {
            com.service.GetUsuariosListResponse _return = new com.service.GetUsuariosListResponse();
            java.util.List<com.service.Usuario> _returnUsuario = new java.util.ArrayList<com.service.Usuario>();
            com.service.Usuario _returnUsuarioVal1 = new com.service.Usuario();
            _returnUsuarioVal1.setApel("Apel1878349789");
            _returnUsuarioVal1.setId(-4964350522468819483l);
            _returnUsuarioVal1.setName("Name-2077081537");
            _returnUsuario.add(_returnUsuarioVal1);
            _return.getUsuario().addAll(_returnUsuario);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.service.UsuarioServcice#addUsuario(com.service.AddUsuario  parameters )*
     */
    public com.service.AddUsuarioResponse addUsuario(AddUsuario parameters) { 
        LOG.info("Executing operation addUsuario");
        System.out.println(parameters);
        try {
            com.service.AddUsuarioResponse _return = new com.service.AddUsuarioResponse();
            com.service.Respuesta _returnRespuesta = new com.service.Respuesta();
            _returnRespuesta.setCodigo(-1039709978);
            _returnRespuesta.setDescripcion("Descripcion1786858389");
            _return.setRespuesta(_returnRespuesta);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.service.UsuarioServcice#updateUsuario(com.service.UpdateUsuario  parameters )*
     */
    public com.service.UpdateUsuarioResponse updateUsuario(UpdateUsuario parameters) throws IOException_Exception    { 
        LOG.info("Executing operation updateUsuario");
        System.out.println(parameters);
        try {
            com.service.UpdateUsuarioResponse _return = new com.service.UpdateUsuarioResponse();
            com.service.Respuesta _returnRespuesta = new com.service.Respuesta();
            _returnRespuesta.setCodigo(1304490912);
            _returnRespuesta.setDescripcion("Descripcion-1870890933");
            _return.setRespuesta(_returnRespuesta);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IOException_Exception("IOException...");
    }

    /* (non-Javadoc)
     * @see com.service.UsuarioServcice#setUsuariosList(java.util.List<com.service.Usuario>  arg0 )*
     */
    public void setUsuariosList(java.util.List<com.service.Usuario> arg0) { 
        LOG.info("Executing operation setUsuariosList");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.service.UsuarioServcice#getUsuario(com.service.GetUsuario  parameters )*
     */
    public com.service.GetUsuarioResponse getUsuario(GetUsuario parameters) { 
        LOG.info("Executing operation getUsuario");
        System.out.println(parameters);
        try {
            com.service.GetUsuarioResponse _return = new com.service.GetUsuarioResponse();
            com.service.Usuario _returnUsuario = new com.service.Usuario();
            _returnUsuario.setApel("Apel-1606778439");
            _returnUsuario.setId(4002126333572168021l);
            _returnUsuario.setName("Name1203670222");
            _return.setUsuario(_returnUsuario);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.service.UsuarioServcice#checkCallWS(int  arg0 )*
     */
    public com.service.Respuesta checkCallWS(int arg0) { 
        LOG.info("Executing operation checkCallWS");
        System.out.println(arg0);
        try {
            com.service.Respuesta _return = new com.service.Respuesta();
            _return.setCodigo(-233684131);
            _return.setDescripcion("Descripcion-1116398994");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.service.UsuarioServcice#deleteUsuario(com.service.Usuario  arg0 )*
     */
    public boolean deleteUsuario(com.service.Usuario arg0) { 
        LOG.info("Executing operation deleteUsuario");
        System.out.println(arg0);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
