
package com.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2016-09-29T10:08:11.008+02:00
 * Generated source version: 2.5.0
 * 
 */
public final class UsuarioServcice_UsuarioServcicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.com/", "UsuarioServciceService");

    private UsuarioServcice_UsuarioServcicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = UsuarioServciceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        UsuarioServciceService ss = new UsuarioServciceService(wsdlURL, SERVICE_NAME);
        UsuarioServcice port = ss.getUsuarioServcicePort();  
        
        {
        System.out.println("Invoking getUsuariosList...");
        com.service.GetUsuariosList _getUsuariosList_parameters = new com.service.GetUsuariosList();
        com.service.GetUsuariosListResponse _getUsuariosList__return = port.getUsuariosList(_getUsuariosList_parameters);
        System.out.println("getUsuariosList.result=" + _getUsuariosList__return);


        }
        {
        System.out.println("Invoking addUsuario...");
        com.service.AddUsuario _addUsuario_parameters = new com.service.AddUsuario();
        com.service.Usuario _addUsuario_parametersArg0 = new com.service.Usuario();
        _addUsuario_parametersArg0.setApel("Apel370987167");
        _addUsuario_parametersArg0.setId(-5104818701392076558l);
        _addUsuario_parametersArg0.setName("Name1311585153");
        _addUsuario_parameters.setArg0(_addUsuario_parametersArg0);
        com.service.AddUsuarioResponse _addUsuario__return = port.addUsuario(_addUsuario_parameters);
        System.out.println("addUsuario.result=" + _addUsuario__return);


        }
        {
        System.out.println("Invoking updateUsuario...");
        com.service.UpdateUsuario _updateUsuario_parameters = new com.service.UpdateUsuario();
        com.service.Usuario _updateUsuario_parametersArg0 = new com.service.Usuario();
        _updateUsuario_parametersArg0.setApel("Apel-652639037");
        _updateUsuario_parametersArg0.setId(9132596531949114929l);
        _updateUsuario_parametersArg0.setName("Name1619867454");
        _updateUsuario_parameters.setArg0(_updateUsuario_parametersArg0);
        try {
            com.service.UpdateUsuarioResponse _updateUsuario__return = port.updateUsuario(_updateUsuario_parameters);
            System.out.println("updateUsuario.result=" + _updateUsuario__return);

        } catch (IOException_Exception e) { 
            System.out.println("Expected exception: IOException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking setUsuariosList...");
        java.util.List<com.service.Usuario> _setUsuariosList_arg0 = new java.util.ArrayList<com.service.Usuario>();
        com.service.Usuario _setUsuariosList_arg0Val1 = new com.service.Usuario();
        _setUsuariosList_arg0Val1.setApel("Apel-482481206");
        _setUsuariosList_arg0Val1.setId(-2138315636229504934l);
        _setUsuariosList_arg0Val1.setName("Name-447705517");
        _setUsuariosList_arg0.add(_setUsuariosList_arg0Val1);
        port.setUsuariosList(_setUsuariosList_arg0);


        }
        {
        System.out.println("Invoking getUsuario...");
        com.service.GetUsuario _getUsuario_parameters = new com.service.GetUsuario();
        _getUsuario_parameters.setArg0(-4038217999627184095l);
        com.service.GetUsuarioResponse _getUsuario__return = port.getUsuario(_getUsuario_parameters);
        System.out.println("getUsuario.result=" + _getUsuario__return);


        }
        {
        System.out.println("Invoking checkCallWS...");
        int _checkCallWS_arg0 = -1967529872;
        com.service.Respuesta _checkCallWS__return = port.checkCallWS(_checkCallWS_arg0);
        System.out.println("checkCallWS.result=" + _checkCallWS__return);


        }
        {
        System.out.println("Invoking deleteUsuario...");
        com.service.Usuario _deleteUsuario_arg0 = new com.service.Usuario();
        _deleteUsuario_arg0.setApel("Apel-1393537472");
        _deleteUsuario_arg0.setId(4593928927285378461l);
        _deleteUsuario_arg0.setName("Name2135395227");
        boolean _deleteUsuario__return = port.deleteUsuario(_deleteUsuario_arg0);
        System.out.println("deleteUsuario.result=" + _deleteUsuario__return);


        }

        System.exit(0);
    }

}
