package com.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2016-09-29T10:08:11.097+02:00
 * Generated source version: 2.5.0
 * 
 */
@WebServiceClient(name = "UsuarioServciceService", 
                  wsdlLocation = "http://localhost:8080/CRUDWSBBDD/services/UsuarioServcicePort?wsdl",
                  targetNamespace = "http://service.com/") 
public class UsuarioServciceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.com/", "UsuarioServciceService");
    public final static QName UsuarioServcicePort = new QName("http://service.com/", "UsuarioServcicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/CRUDWSBBDD/services/UsuarioServcicePort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UsuarioServciceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/CRUDWSBBDD/services/UsuarioServcicePort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UsuarioServciceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UsuarioServciceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UsuarioServciceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UsuarioServciceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UsuarioServciceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UsuarioServciceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns UsuarioServcice
     */
    @WebEndpoint(name = "UsuarioServcicePort")
    public UsuarioServcice getUsuarioServcicePort() {
        return super.getPort(UsuarioServcicePort, UsuarioServcice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UsuarioServcice
     */
    @WebEndpoint(name = "UsuarioServcicePort")
    public UsuarioServcice getUsuarioServcicePort(WebServiceFeature... features) {
        return super.getPort(UsuarioServcicePort, UsuarioServcice.class, features);
    }

}
